"""The product layer: branded chat app, conversational voice, owner approvals.

Covers what turned "an API with a demo page" into a product, while the brain
stays 100% local (no external AI, no external API keys):

- ``/``            the branded chat app (logo, favicon, session sidebar,
                   markdown, streaming reveal, typing state, mobile layout)
- ``/developers``  the portal: a live endpoint table from ``/api.json`` plus
                   the key-request form
- ``/approve``     the owner's approval inbox, web-token gated
- conversation     multi-turn context, memory recall, honest scope
- email            stdlib SMTP so key requests reach the owner twice over
- parity           the threaded server serves the same surface as serverless
- serve            ``REALAI_*`` environment variables are honoured

Nothing here touches the network: SMTP is a fake object, HTTP is either
``WebApp.handle`` directly or a server bound to 127.0.0.1.
"""

import json
import os
import smtplib
import unittest
from unittest import mock

from .helpers import ApiClient, make_agent, register_device, start_server

from realaiagent import web_pages
from realaiagent.api import routes as R
from realaiagent.config import Config
from realaiagent.conversation import ConversationManager
from realaiagent.email import EmailNotifier, parse_recipients
from realaiagent.web import WebApp


def call(app, method, path, query=None, headers=None, body=b""):
    return app.handle(method, path, query or {}, headers or {}, body)


def jbody(body):
    return json.loads(body.decode("utf-8"))


def text(body):
    return body.decode("utf-8")


# --------------------------------------------------------------- fake SMTP

class FakeSMTP:
    """Stand-in for ``smtplib.SMTP``: records everything, sends nothing."""

    instances = []

    def __init__(self, host, port, timeout=None, context=None):
        self.host = host
        self.port = port
        self.timeout = timeout
        self.context = context
        self.sent = []
        self.ehlo_calls = 0
        self.started_tls = False
        self.logged_in = None
        self.quit_called = False
        FakeSMTP.instances.append(self)

    def ehlo(self):
        self.ehlo_calls += 1

    def starttls(self, context=None):
        self.started_tls = True

    def login(self, user, password):
        self.logged_in = (user, password)

    def send_message(self, msg, from_addr=None, to_addrs=None):
        self.sent.append({"subject": msg["Subject"], "from": from_addr,
                          "to": list(to_addrs or []),
                          "body": msg.get_content()})

    def quit(self):
        self.quit_called = True

    def close(self):
        pass


class BrokenSMTP:
    """An SMTP host that refuses everything — mail must never propagate."""

    def __init__(self, *args, **kwargs):
        raise OSError("connection refused")


# =========================================================== the chat app at /

class TestBrandedChatApp(unittest.TestCase):
    def setUp(self):
        self.agent = make_agent()
        self.app = WebApp(self.agent)
        self.page = text(call(self.app, "GET", "/")[2])

    def test_root_serves_the_branded_chat_app(self):
        status, ctype, body, _extra = call(self.app, "GET", "/")
        self.assertEqual(status, 200)
        self.assertIn("text/html", ctype)
        page = text(body)
        # the product chrome: wordmark, session sidebar, composer
        self.assertIn("<aside class=\"side\" id=\"sidebar\">", page)
        self.assertIn("id=\"composer\"", page)
        self.assertIn("id=\"newchat\"", page)
        # markdown + streaming reveal + typing state, all client side
        self.assertIn("function md(", page)
        self.assertIn("function reveal(", page)
        self.assertIn("id=\"typing\"", page)
        # sessions survive a reload without cookies
        self.assertIn("localStorage", page)
        self.assertIn(self.agent.mind.agent_name, page)

    def test_root_carries_its_own_logo_and_favicon(self):
        self.assertIn('rel="icon"', self.page)
        self.assertIn("/logo.svg", self.page)
        self.assertIn('rel="alternate icon"', self.page)
        # the mark is generated by this repo, not fetched from a CDN
        self.assertIn("<svg viewBox=\"0 0 64 64\"", self.page)
        self.assertIn('name="theme-color"', self.page)
        self.assertNotIn("cdn.", self.page.lower())
        self.assertNotIn("googleapis", self.page.lower())

    def test_root_advertises_the_keyless_demo(self):
        # the demo is open; the API is not (see the /v1 tests below)
        self.assertIn("talk to it", self.page)
        self.assertIn("/public/chat", self.page)
        self.assertIn("no key needed", self.page)
        self.assertIn("/developers", self.page)

    def test_root_is_mobile_aware(self):
        self.assertIn('name="viewport"', self.page)
        self.assertIn("width=device-width", self.page)
        self.assertIn("@media (max-width: 860px)", self.page)
        self.assertIn('id="burger"', self.page)
        self.assertIn("prefers-reduced-motion", self.page)

    def test_root_has_the_senior_chatgpt_grade_layout(self):
        # app shell: sidebar + centered empty state + pill composer dock
        self.assertIn('class="shell"', self.page)
        self.assertIn('id="hero"', self.page)
        self.assertIn("What can I help with?", self.page)
        self.assertIn('class="composer"', self.page)
        self.assertIn('class="sbtn send"', self.page)
        self.assertIn("data-msg=", self.page)      # suggestion chips
        self.assertIn('id="sessfilter"', self.page)  # searchable sidebar
        self.assertIn('id="agentstatus"', self.page)  # live mood line
        self.assertIn('id="scrim"', self.page)
        self.assertIn("100dvh", self.page)

    def test_root_supports_light_and_dark_themes(self):
        self.assertIn('data-theme="light"', self.page)
        self.assertIn("[data-theme=\"dark\"]", self.page)
        self.assertIn("prefers-color-scheme", self.page)  # theme boot
        self.assertIn("data-themebtn", self.page)         # toggle
        self.assertIn("realai.theme", self.page)          # persisted

    def test_inline_icons_are_safe_js_strings(self):
        # the chrome JS splices SVG icons into double-quoted JS literals;
        # unescaped quotes there used to break the whole page's script
        self.assertIn(
            'var ICON_SUN="<svg viewBox=\\"0 0 24 24\\"', self.page)
        self.assertIn(
            'var MARK = "<svg viewBox=\\"0 0 64 64\\"', self.page)

    def test_root_carries_the_count_ring_mark(self):
        # the 0.7.0 mark: an arc with a 72-degree gap + one dot in it
        self.assertIn('class="mark"', self.page)
        self.assertIn("A20 20 0 1 1", self.page)   # the open ring
        self.assertIn('<circle class="md"', self.page)  # the counted dot
        self.assertIn('cx="43.47" cy="15.62"', self.page)
        # favicon / logo endpoints serve the tile variant (dark squircle)
        for path in ("/logo.svg", "/favicon.ico"):
            _s, _c, body, _x = call(self.app, "GET", path)
            self.assertIn(b"<rect", body, path)
            self.assertIn(b'rx="14.5"', body, path)
            self.assertIn(b"#0f1115", body, path)

    def test_page_escapes_the_agent_identity(self):
        self.agent.mind.set_identity(agent_name='<script>alert(1)</script>')
        page = text(call(self.app, "GET", "/")[2])
        self.assertNotIn("<script>alert(1)</script>", page)
        self.assertIn("&lt;script&gt;alert(1)", page)

    def test_brand_assets_are_served_as_svg(self):
        for path in ("/logo.svg", "/favicon.ico"):
            status, ctype, body, extra = call(self.app, "GET", path)
            self.assertEqual(status, 200, path)
            self.assertEqual(ctype, "image/svg+xml", path)
            self.assertTrue(body.startswith(b"<svg"), path)
            self.assertIn("Cache-Control", extra)

    def test_markdown_renders_structure(self):
        out = web_pages.markdown_to_html(
            "# Title\n\nsome **bold** and `code`\n\n- one\n- two\n\n"
            "1. first\n2. second")
        self.assertIn("<h3>Title</h3>", out)
        self.assertIn("<strong>bold</strong>", out)
        self.assertIn("<code>code</code>", out)
        self.assertIn("<ul>", out)
        self.assertIn("<li>one</li>", out)
        self.assertIn("<ol>", out)
        self.assertIn("<li>second</li>", out)

    def test_markdown_escapes_html_and_refuses_javascript_links(self):
        out = web_pages.markdown_to_html("<script>alert(1)</script>")
        self.assertNotIn("<script>", out)
        self.assertIn("&lt;script&gt;", out)
        # a javascript: URL must never become clickable
        out = web_pages.markdown_to_html("[click](javascript:alert(1))")
        self.assertNotIn("<a href=\"javascript", out)
        self.assertIn("click", out)
        # but a real link is fine
        out = web_pages.markdown_to_html("[portal](/developers)")
        self.assertIn('<a href="/developers">portal</a>', out)

    def test_markdown_keeps_code_fences_verbatim(self):
        out = web_pages.markdown_to_html("```\nrm -rf / && <b>x</b>\n```")
        self.assertIn("<pre><code>", out)
        self.assertIn("rm -rf / &amp;&amp; &lt;b&gt;x&lt;/b&gt;", out)
        self.assertNotIn("<b>x</b>", out)

    def test_threaded_server_serves_the_same_surface(self):
        """Parity: what serverless serves, ``python -m realaiagent serve``
        serves too. The threaded server used to run ``dispatch`` directly and
        404'd on everything the web layer adds."""
        server = start_server(self.agent)
        try:
            base = f"http://127.0.0.1:{server.bound_port}"
            anon = ApiClient(base, None)
            for path in ("/", "/developers", "/logo.svg", "/favicon.ico",
                         "/approve", "/dashboard", "/api.json", "/healthz"):
                code, body = anon.req("GET", path)
                self.assertEqual(code, 200, path)
                self.assertTrue(body, path)
            code, body = anon.req("POST", "/public/chat",
                                  {"message": "hello there"})
            self.assertEqual(code, 200)
            self.assertIn("response", body)
            # ...and the gate still holds on the threaded server
            code, _ = anon.req("GET", "/v1/status")
            self.assertEqual(code, 401)
            code, _ = anon.req("GET", "/stream")
            self.assertEqual(code, 200)
            # A crash in the web layer must come back as the same JSON 500
            # the serverless handler gives (and be counted), not as a
            # dropped connection from a dead worker thread.
            real_handle = server.web.handle

            def explode(*a, **kw):
                raise RuntimeError("page renderer exploded")

            server.web.handle = explode
            try:
                code, body = anon.req("GET", "/developers")
            finally:
                server.web.handle = real_handle
            self.assertEqual(code, 500)
            self.assertEqual(body["error"]["code"], "internal")
            self.assertGreaterEqual(
                self.agent.storage.get_counters()
                .get("errors", {}).get("http_500", 0), 1)
            # and the server keeps serving afterwards
            code, _ = anon.req("GET", "/healthz")
            self.assertEqual(code, 200)
        finally:
            server.shutdown()
            self.agent.stop()


# ======================================================= keyless demo chat

class TestKeylessDemoChat(unittest.TestCase):
    def setUp(self):
        self.agent = make_agent()
        self.agent.cfg.demo_rate_per_min = 600
        self.agent.cfg.demo_burst = 50
        self.app = WebApp(self.agent)
        # the default limiter is module-global: start each test empty
        R._public_demo_limiter.reset()

    def tearDown(self):
        R._public_demo_limiter.reset()

    def post(self, message, headers=None, session_id="__unset__"):
        payload = {"message": message}
        if session_id != "__unset__":
            payload["session_id"] = session_id
        return call(self.app, "POST", "/public/chat",
                    headers=headers or {"x-forwarded-for": "203.0.113.7"},
                    body=json.dumps(payload).encode())

    def test_chat_returns_and_reuses_a_session_id(self):
        status, _ctype, body, _extra = self.post("hello there")
        self.assertEqual(status, 200)
        first = jbody(body)
        self.assertIn("response", first)
        self.assertEqual(first["meta"]["intent"], "greet")
        self.assertTrue(first["session_id"])

        status, _ctype, body, _extra = self.post(
            "what do you think", session_id=first["session_id"])
        second = jbody(body)
        self.assertEqual(second["session_id"], first["session_id"])
        self.assertEqual(second["meta"]["context"]["turn"], 1)
        self.assertTrue(second["meta"]["voice"])

    def test_chat_validates_its_input(self):
        status, _c, body, _x = self.post("")
        self.assertEqual(status, 400)
        self.assertEqual(jbody(body)["error"]["code"], "bad_request")

        status, _c, body, _x = self.post("x" * 4001)
        self.assertEqual(status, 400)
        self.assertIn("too long", jbody(body)["error"]["message"])

        status, _c, body, _x = self.post("hi", session_id=12345)
        self.assertEqual(status, 400)
        self.assertIn("session_id", jbody(body)["error"]["message"])

    def test_demo_rate_limit_is_per_visitor(self):
        """One rude guest must not exhaust the demo for everyone else."""
        self.agent.cfg.demo_rate_per_min = 0
        self.agent.cfg.demo_burst = 1

        rude = {"x-forwarded-for": "198.51.100.1"}
        other = {"x-forwarded-for": "198.51.100.2"}
        self.assertEqual(self.post("hello", headers=rude)[0], 200)
        status, _c, body, _x = self.post("hello again", headers=rude)
        self.assertEqual(status, 429)
        self.assertEqual(jbody(body)["error"]["code"], "rate_limited")
        # a different visitor still has their own full bucket
        self.assertEqual(self.post("hello", headers=other)[0], 200)

        # the header that identifies the visitor is read from the proxy chain
        self.assertEqual(
            R.visitor_id({"headers": {"x-forwarded-for": "9.9.9.9, 10.0.0.1"}}),
            "9.9.9.9")
        self.assertEqual(R.visitor_id({"headers": {}}), "anonymous")

        # and the limiter itself keeps one bucket per visitor
        limiter = R._PublicLimiter(rate_per_min=0, burst=1)
        self.assertTrue(limiter.allow("a"))
        self.assertFalse(limiter.allow("a"))
        self.assertTrue(limiter.allow("b"))
        self.assertEqual(limiter.visitors(), 2)

    def test_visitor_buckets_are_pruned(self):
        limiter = R._PublicLimiter(rate_per_min=60, burst=5, max_visitors=16)
        for index in range(60):
            limiter.allow(f"10.0.0.{index}")
        self.assertLessEqual(limiter.visitors(), 16)
        # still usable after pruning
        self.assertTrue(limiter.allow("10.0.99.99"))

    def test_demo_chat_cannot_reach_owner_commands(self):
        """Keyless means scope-less: the permission gate still applies."""
        status, _c, body, _x = self.post("approve 1")
        self.assertEqual(status, 200)
        self.assertIn("Only my owner", jbody(body)["response"])
        status, _c, body, _x = self.post("goal: delete everything")
        self.assertIn("Only my owner", jbody(body)["response"])

    def test_demo_chat_feeds_the_plans_stream(self):
        self.post("status")
        _last, items = self.app.hub.read("plans", 0, wait=0)
        self.assertTrue(items)
        self.assertIn("intent", items[-1]["data"])


# ==================================================== the conversational voice

class TestConversationalVoice(unittest.TestCase):
    def setUp(self):
        self.agent = make_agent()
        register_device(self.agent, did="lamp-1", name="Living Room Lamp")
        self.sid = "s-voice"

    def say(self, message, session_id=None):
        return self.agent.reply(message, session_id=session_id or self.sid,
                                sender="web")

    # ---- honest scope: it never pretends to have what it does not have

    def test_honest_about_no_internet(self):
        out = self.say("can you search the web for that?")
        self.assertEqual(out["meta"]["intent"], "scope")
        self.assertIn("no internet access", out["response"])
        # ...and it offers what it CAN do rather than just refusing
        self.assertIn("ledger", out["response"])
        self.assertIn("counters", out["response"])

    def test_honest_about_no_external_ai(self):
        out = self.say("just ask chatgpt to write it")
        self.assertIn("no other AI inside me", out["response"])
        self.assertIn("trainable", out["response"])

    def test_honest_about_no_media_generation(self):
        out = self.say("draw me a picture of a cat")
        self.assertIn("cannot make images", out["response"])
        out = self.say("sing me a song")
        self.assertIn("cannot make images", out["response"])

    def test_honest_about_no_live_data(self):
        out = self.say("what is the weather today")
        self.assertIn("cannot see live data", out["response"])
        out = self.say("what's the stock price of AAPL")
        self.assertIn("cannot see live data", out["response"])

    def test_answers_questions_about_itself_honestly(self):
        out = self.say("are you alive?")
        self.assertEqual(out["meta"]["intent"], "identity")
        self.assertIn("Honestly? No", out["response"])
        self.assertIn("valence", out["response"])

        out = self.say("who made you?", session_id="s-who")
        self.assertIn(self.agent.mind.owner_name, out["response"])
        self.assertIn("standard library", out["response"])

        # ...and it greets a stranger like a stranger, not like the owner
        self._visitor_greeting_is_not_the_owner_greeting()

    def _visitor_greeting_is_not_the_owner_greeting(self):
        """Folded into the identity test above: the engine writes its hello
        for the owner ("Hello Boss"), which is right on Telegram and on an
        owner key and wrong on a public web page. The web voice adapts;
        /v1/chat keeps the engine's own words."""
        first = self.say("hello there", session_id="s-hi")
        self.assertEqual(first["meta"]["intent"], "greet")
        self.assertNotIn("Boss", first["response"])
        self.assertIn(self.agent.mind.agent_name, first["response"])
        self.assertIn("pure Python", first["response"])
        self.assertIn("no external AI", first["response"])
        self.assertIn("status", first["response"])

        # a returning visitor is not re-introduced to everything
        again = self.say("hi", session_id="s-hi")
        self.assertIn("again", again["response"].lower())
        self.assertNotIn("from scratch", again["response"])

        # thanks does not call a stranger "boss" either
        self.assertNotIn("boss", self.say("thanks", session_id="s-ta")[
            "response"].lower())

        # ...and the owner path is untouched
        owner = self.agent.reply("hello there", session_id="s-owner",
                                 sender="boss", scopes=["owner"])
        self.assertEqual(owner["meta"]["intent"], "greet")
        self.assertIn("Boss", owner["response"])

    # ---- memory recall: only ever quotes a real row

    def test_recalls_what_you_told_it(self):
        first = self.say("remember that the workshop lamp is called Bessie")
        self.assertEqual(first["meta"]["intent"], "learn")

        # a message the parser cannot place is still answered *from* memory
        second = self.say("what about the workshop lamp?")
        self.assertTrue(second["meta"]["recall"])
        self.assertIn("Bessie", second["meta"]["recall"][0])
        self.assertIn("Bessie", second["response"])
        self.assertIn("my memory does have something", second["response"])
        # ...and it is quoted once, not twice
        self.assertEqual(second["response"].count("Bessie"), 1)

        # a message the parser *does* place gets the memory as a tail
        third = self.say("remember that Bessie lives in the workshop")
        self.assertIn("I also remember you told me", third["response"])
        self.assertTrue(third["meta"]["recall"])

        # nothing recalled when nothing matches: recall is never invented
        blank = self.say("status", session_id="s-fresh")
        self.assertEqual(blank["meta"]["recall"], [])

    # ---- multi-turn context

    def test_followup_again_repeats_the_last_answer(self):
        first = self.say("status")
        out = self.say("again")
        self.assertEqual(out["meta"]["intent"], "repeat")
        self.assertIn("once more", out["response"])
        self.assertIn(first["response"].splitlines()[0][:20], out["response"])

    def test_followup_more_elaborates(self):
        self.say("status")
        out = self.say("tell me more")
        self.assertEqual(out["meta"]["intent"], "elaborate")
        self.assertIn("By the numbers", out["response"])
        self.assertIn("goal queue", out["response"])

    def test_followup_next_reports_the_queue(self):
        self.agent.mind.add_goal("watch the workshop", priority=0.9)
        self.say("hello there")   # a follow-up needs something to follow
        out = self.say("and now?")
        self.assertEqual(out["meta"]["intent"], "next")
        self.assertIn("Autonomy is", out["response"])
        self.assertIn("watch the workshop", out["response"])

    def test_resolves_pronouns_to_the_last_device(self):
        self.say("turn on the Living Room Lamp")
        out = self.say("now turn it off")
        context = out["meta"]["context"]
        self.assertTrue(context["resolved"])
        self.assertEqual(context["kind"], "device_anaphora")
        self.assertEqual(context["device"], "lamp-1")
        self.assertIn("turn off the Living Room Lamp", out["response"])

        # "set it to 21" carries the number across too
        out = self.say("set it to 21")
        self.assertIn("21", out["response"])

        # an explicit instruction is never rewritten against the old topic
        out = self.say("remember that the kitchen light is called Kit")
        self.assertEqual(out["meta"]["intent"], "learn")

    # ---- sessions live in the database, so they survive a cold start

    def test_turns_are_persisted_and_rehydrated(self):
        self.say("hello there")
        self.say("status")
        rows = self.agent.storage.session_turns(self.sid)
        self.assertEqual(len(rows), 2)
        self.assertEqual(rows[0]["message"], "hello there")
        self.assertEqual(rows[-1]["intent"], "status")

        # a brand new manager (what a frozen serverless function becomes)
        # reads the same history straight back out of sqlite
        fresh = ConversationManager(self.agent)
        session = fresh.session(self.sid)
        self.assertEqual(session.turn_count, 2)
        out = fresh.reply("again", session_id=self.sid, sender="web")
        self.assertIn("once more", out["response"])
        self.assertIn(self.sid, fresh.sessions())

        # History is trimmed, because a public page mints sessions forever and
        # an unbounded session_turns table is how a small box fills its disk.
        storage = self.agent.storage
        for i in range(12):
            storage.session_add_turn("s-flood", f"m{i}", f"r{i}")
        storage.session_add_turn(self.sid, "keep me", "kept")
        deleted = storage.session_prune(keep_per_session=3)
        self.assertEqual(deleted, 10)
        left = storage.session_turns("s-flood", 100)
        self.assertEqual([r["message"] for r in left], ["m9", "m10", "m11"])
        self.assertEqual(storage.session_count(self.sid), 3)
        # ...and there is a global ceiling across every session
        self.assertEqual(storage.session_prune(max_rows=2), 4)
        self.assertEqual(len(storage.query(
            "SELECT id FROM session_turns")), 2)
        # pruning an empty table is a no-op that reports nothing deleted
        storage.execute("DELETE FROM session_turns")
        self.assertEqual(storage.session_prune(), 0)

        # ...and it also runs by itself, so a public server left running for
        # weeks cannot grow the table without bound
        real_every = type(storage).SESSION_PRUNE_EVERY
        real_keep = type(storage).SESSION_KEEP_PER_SESSION
        type(storage).SESSION_PRUNE_EVERY = 4
        type(storage).SESSION_KEEP_PER_SESSION = 2
        try:
            for i in range(8):
                storage.session_add_turn("s-auto", f"a{i}", f"b{i}")
        finally:
            type(storage).SESSION_PRUNE_EVERY = real_every
            type(storage).SESSION_KEEP_PER_SESSION = real_keep
        self.assertEqual(storage.session_count("s-auto"), 2)
        self.assertEqual([r["message"] for r in
                          storage.session_turns("s-auto", 10)], ["a6", "a7"])

    def test_session_ids_are_validated_and_forgettable(self):
        out = self.say("hello", session_id="../../etc/passwd")
        self.assertNotEqual(out["session_id"], "../../etc/passwd")
        self.assertTrue(out["session_id"].startswith("s-"))

        out = self.say("hello", session_id="x" * 400)
        self.assertTrue(out["session_id"].startswith("s-"))

        self.say("hello there")
        self.assertTrue(self.agent.storage.session_turns(self.sid))
        self.assertTrue(self.agent.conversation.forget(self.sid))
        self.assertEqual(self.agent.storage.session_turns(self.sid), [])
        self.assertEqual(self.agent.conversation.session(self.sid).turn_count,
                         0)


# ====================================================== the developer portal

class TestDeveloperPortal(unittest.TestCase):
    def setUp(self):
        self.agent = make_agent()
        self.app = WebApp(self.agent)
        status, ctype, body, _x = call(
            self.app, "GET", "/developers",
            headers={"host": "realai.example"})
        self.assertEqual(status, 200)
        self.assertIn("text/html", ctype)
        self.page = text(body)

    def test_portal_serves_a_live_endpoint_table(self):
        self.assertIn("Developers", self.page)
        self.assertIn("live endpoint table", self.page.lower())
        self.assertIn("id=\"endpoints\"", self.page)
        for path in ("/v1/chat", "/v1/status", "/public/chat", "/developers",
                     "/api.json", "/healthz"):
            self.assertIn(path, self.page)
        # the table is generated from the registry, so hosts are live too
        self.assertIn("realai.example", self.page)
        self.assertIn("Authorization: Bearer", self.page)

    def test_portal_table_matches_api_json(self):
        _status, _c, body, _x = call(self.app, "GET", "/api.json")
        payload = jbody(body)
        rows = payload["routes"]
        self.assertGreater(len(rows), 30)
        page = web_pages.developers_page(self.agent, rows)
        for route in rows:
            self.assertIn(route["path"], page)
        # one rendered row per live route, from the shared helper
        self.assertEqual(web_pages.endpoint_rows(rows).count("<tr>"), len(rows))
        self.assertIn(f"live endpoint table · {len(rows)} routes", page)

    def test_portal_marks_public_and_owner_routes(self):
        self.assertIn('<span class="pill pub">public</span>', self.page)
        self.assertIn('<span class="pill own">owner</span>', self.page)
        self.assertIn("chat", self.page)
        # a route that is not documented still renders, with an em dash
        rows = web_pages.endpoint_rows(
            [{"method": "GET", "path": "/v1/mystery", "scopes": ["admin"]}])
        self.assertIn("/v1/mystery", rows)
        self.assertIn("admin", rows)
        self.assertIn("—", rows)
        self.assertIn("no routes", web_pages.endpoint_rows([]))

    def test_portal_has_the_key_request_form(self):
        self.assertIn("id=\"reqform\"", self.page)
        self.assertIn("id=\"username\"", self.page)
        self.assertIn("/v1/users/request", self.page)
        self.assertIn("PENDING", self.page)
        self.assertIn("email", self.page.lower())

    def test_portal_documents_limits_and_errors(self):
        for code in ("401 unauthorized", "402 insufficient_funds",
                     "403 forbidden", "429 rate_limited", "413 body_too_large",
                     "500 internal"):
            self.assertIn(code, self.page)
        self.assertIn("Rate limits", self.page)
        self.assertIn("Billing", self.page)
        self.assertIn("Everything counted", self.page)

    def test_key_request_reaches_the_owner_by_email(self):
        """The owner hears about a key request on Telegram AND email."""
        FakeSMTP.instances = []
        notifier = EmailNotifier(host="smtp.test", port=587, user="me@test",
                                 password="app-password", sender="me@test",
                                 recipients="owner@test", mode="starttls",
                                 storage=self.agent.storage)
        self.agent.users.mailer = notifier
        with mock.patch.object(smtplib, "SMTP", FakeSMTP):
            status, _c, body, _x = call(
                self.app, "POST", "/v1/users/request", {}, {},
                json.dumps({"username": "mira",
                            "note": "a workshop dashboard"}).encode())
        self.assertEqual(status, 200)
        self.assertEqual(jbody(body)["status"], "PENDING")
        self.assertEqual(len(FakeSMTP.instances), 1)
        mail = FakeSMTP.instances[0].sent[0]
        self.assertIn("access request", mail["subject"])
        self.assertIn("mira", mail["subject"])
        self.assertIn("PENDING", mail["body"])
        self.assertIn("a workshop dashboard", mail["body"])
        # the request is really queued for the owner to decide
        self.assertEqual(self.agent.users.list("PENDING")[0]["username"],
                         "mira")

    def test_key_request_still_works_over_the_api(self):
        status, _c, body, _x = call(
            self.app, "POST", "/v1/users/request", {}, {},
            json.dumps({"username": "api-person"}).encode())
        self.assertEqual(status, 200)
        self.assertEqual(jbody(body)["status"], "PENDING")
        # ...and an empty username is still refused
        status, _c, body, _x = call(
            self.app, "POST", "/v1/users/request", {}, {},
            json.dumps({"username": ""}).encode())
        self.assertEqual(status, 400)


# ================================================== the owner approval inbox

class TestOwnerApprovalInbox(unittest.TestCase):
    def setUp(self):
        self.agent = make_agent()
        self.agent.cfg.web_token = "sekret-token"
        self.app = WebApp(self.agent)
        self.agent.users.request("mira", note="workshop dashboard")
        self.agent.users.request("bob")
        self.good = {"x-web-token": "sekret-token"}

    def post(self, payload, headers=None):
        return call(self.app, "POST", "/approve",
                    headers=headers if headers is not None else self.good,
                    body=json.dumps(payload).encode())

    def test_inbox_requires_the_web_token(self):
        status, _c, body, _x = call(self.app, "GET", "/approve")
        self.assertEqual(status, 401)
        self.assertEqual(jbody(body)["error"]["code"], "unauthorized")
        self.assertIn("REALAI_WEB_TOKEN", jbody(body)["error"]["message"])

        status, _c, body, _x = call(self.app, "GET", "/approve",
                                    {"token": "wrong"})
        self.assertEqual(status, 401)

        status, _c, body, _x = call(self.app, "GET", "/approve",
                                    {"token": "sekret-token"})
        self.assertEqual(status, 200)
        # a decision needs the token too
        status, _c, body, _x = self.post({"action": "approve",
                                          "username": "mira"}, headers={})
        self.assertEqual(status, 401)
        self.assertEqual(self.agent.storage.user_get("mira")["status"],
                         "PENDING")

        # ...and wrong tokens are counted per visitor: after a handful of
        # failures the gate locks the visitor out with a 429 instead of
        # letting a browser script keep guessing the secret.
        guard = self.app.token_guard
        guard.max_failures = 3
        guard.lockout_s = 60.0
        alerts: list = []
        real_send = self.agent.telegram.send
        self.agent.telegram.send = lambda text, **kw: alerts.append(text)
        try:
            for _ in range(2):
                status, _c, _b, _x = call(self.app, "GET", "/approve",
                                          {"token": "wrong"}, {})
                self.assertEqual(status, 401)
            status, _c, body, _x = call(self.app, "GET", "/approve",
                                        {"token": "wrong"}, {})
        finally:
            self.agent.telegram.send = real_send
        self.assertEqual(status, 429)
        self.assertEqual(jbody(body)["error"]["code"], "too_many_attempts")
        # the owner hears about a brute-force attempt once, not per hit
        self.assertEqual(len(alerts), 1)
        self.assertIn("locked out", alerts[0])
        # the right token is refused too while the lockout stands
        status, _c, _b, _x = call(self.app, "GET", "/approve",
                                  {"token": "sekret-token"}, {})
        self.assertEqual(status, 429)
        # a browser reload of the inbox gets the human-readable 429 page
        status, ctype, body, extra = call(
            self.app, "GET", "/approve", {"token": "wrong"},
            {"accept": "text/html"})
        self.assertEqual(status, 429)
        self.assertIn("text/html", ctype)
        self.assertIn("Too many wrong web tokens", body.decode())
        self.assertTrue(extra.get("Retry-After"))
        # the attempt is on the ledger
        counts = self.agent.storage.get_counters()
        self.assertGreaterEqual(
            counts.get("security", {}).get("web_token_denied", 0), 3)
        self.assertGreaterEqual(
            counts.get("security", {}).get("web_token_lockout", 0), 1)
        self.assertTrue(self.agent.storage.query(
            "SELECT id FROM events WHERE type='intrusion'"))
        # /dashboard and /stream honour the same gate
        status, _c, _b, _x = call(self.app, "GET", "/dashboard", {}, {})
        self.assertEqual(status, 429)
        status, _c, _b, _x = call(self.app, "GET", "/stream", {}, {})
        self.assertEqual(status, 429)
        # and a clean visitor with the right token is let through, which also
        # clears their record
        guard.succeed("local")
        status, _c, _b, _x = call(self.app, "GET", "/dashboard",
                                  {"token": "sekret-token"}, {})
        self.assertEqual(status, 200)
        self.assertEqual(guard.blocked_for("local"), 0.0)
        # the token is never accepted from a body: a cross-site form can post
        # one, it cannot set a custom header
        status, _c, body, _x = call(self.app, "POST", "/approve", {}, {},
                                    json.dumps({"action": "approve",
                                                "username": "mira",
                                                "token": "sekret-token"
                                                }).encode())
        self.assertEqual(status, 401)


    def test_browser_gets_a_token_gate_page(self):
        status, ctype, body, _x = call(
            self.app, "GET", "/approve", {},
            {"accept": "text/html,application/xhtml+xml"})
        self.assertEqual(status, 401)
        self.assertIn("text/html", ctype)
        page = text(body)
        self.assertIn("REALAI_WEB_TOKEN", page)
        self.assertIn('name="token"', page)
        self.assertIn("/approve", page)

    def test_inbox_lists_pending_clients(self):
        status, _c, body, _x = call(self.app, "GET", "/approve", {}, self.good)
        self.assertEqual(status, 200)
        page = text(body)
        self.assertIn("Approvals", page)
        self.assertIn("mira", page)
        self.assertIn("bob", page)
        self.assertIn("waiting for you · 2", page)
        self.assertIn(">Approve<", page)
        self.assertIn(">Deny<", page)
        # the token is handed to the page's own buttons, nothing else leaks
        self.assertIn("sekret-token", page)
        self.assertNotIn("rxa_", page)

    def test_approve_mints_a_key_shown_once(self):
        FakeSMTP.instances = []
        notifier = EmailNotifier(host="smtp.test", port=587, user="me@test",
                                 password="pw", sender="me@test",
                                 recipients="owner@test",
                                 storage=self.agent.storage)
        self.agent.users.mailer = notifier
        with mock.patch.object(smtplib, "SMTP", FakeSMTP):
            status, _c, body, _x = self.post({"action": "approve",
                                              "username": "mira"})
        self.assertEqual(status, 200)
        out = jbody(body)
        self.assertTrue(out["api_key"].startswith("rxa_"))
        self.assertTrue(out["key_id"])
        self.assertEqual(sorted(out["key_scopes"]),
                         ["chat", "devices", "learn"])
        self.assertEqual(out["status"], "APPROVED")
        self.assertEqual(self.agent.storage.user_get("mira")["status"],
                         "APPROVED")

        # a new client starts billed with a zero balance, so the owner's
        # next tap matters: without VIP (or a top-up) the key gets 402
        status, _c, body, _x = call(
            self.app, "GET", "/v1/status", {},
            {"authorization": f"Bearer {out['api_key']}"})
        self.assertEqual(status, 402)
        self.post({"action": "vip", "username": "mira", "vip": True})
        # now the minted key really works, and the inbox never re-renders it
        status, _c, body, _x = call(
            self.app, "GET", "/v1/status", {},
            {"authorization": f"Bearer {out['api_key']}"})
        self.assertEqual(status, 200)
        page = text(call(self.app, "GET", "/approve", {}, self.good)[2])
        self.assertNotIn(out["api_key"], page)
        # ...and a plaintext secret is never emailed to anyone
        for instance in FakeSMTP.instances:
            for mail in instance.sent:
                self.assertNotIn("rxa_", mail["body"])

    def test_deny_bans_and_unban_restores(self):
        status, _c, body, _x = self.post({"action": "approve",
                                          "username": "mira"})
        key = jbody(body)["api_key"]
        status, _c, body, _x = self.post({"action": "deny", "username": "mira"})
        self.assertEqual(status, 200)
        self.assertEqual(jbody(body)["status"], "BANNED")
        self.assertEqual(self.agent.storage.user_get("mira")["status"], "BANNED")
        # their key was revoked with them
        status, _c, _b, _x = call(self.app, "GET", "/v1/status", {},
                                  {"authorization": f"Bearer {key}"})
        self.assertEqual(status, 401)

        status, _c, body, _x = self.post({"action": "unban", "username": "mira"})
        self.assertEqual(jbody(body)["status"], "PENDING")

    def test_vip_toggle_changes_billing(self):
        self.post({"action": "approve", "username": "bob"})
        self.assertFalse(self.agent.storage.user_get("bob")["is_vip"])

        status, _c, body, _x = self.post({"action": "vip", "username": "bob",
                                          "vip": True})
        self.assertEqual(status, 200)
        self.assertTrue(jbody(body)["is_vip"])
        self.assertTrue(self.agent.storage.user_get("bob")["is_vip"])

        status, _c, body, _x = self.post({"action": "vip", "username": "bob",
                                          "vip": False})
        self.assertFalse(jbody(body)["is_vip"])

    def test_inbox_rejects_bad_input(self):
        status, _c, body, _x = self.post({"action": "promote",
                                          "username": "mira"})
        self.assertEqual(status, 400)
        self.assertIn("approve|deny|unban|vip",
                      jbody(body)["error"]["message"])

        status, _c, body, _x = self.post({"action": "approve", "username": ""})
        self.assertEqual(status, 400)

        status, _c, body, _x = self.post({"action": "approve",
                                          "username": "nobody-here"})
        self.assertEqual(status, 404)

        status, _c, _b, _x = call(self.app, "DELETE", "/approve", {}, self.good)
        self.assertEqual(status, 405)

        # The gate is checked *before* the body is parsed, so a malformed
        # body from an ungated visitor is still just 401.
        status, _c, body, _x = call(self.app, "POST", "/approve", {}, {},
                                    b"{oops")
        self.assertEqual(status, 401)

        status, _c, body, _x = call(self.app, "POST", "/approve", {},
                                    self.good, b"{oops")
        self.assertEqual(status, 400)
        self.assertEqual(jbody(body)["error"]["code"], "bad_json")


# ============================================================ owner email

class TestOwnerEmail(unittest.TestCase):
    def setUp(self):
        self.agent = make_agent()
        FakeSMTP.instances = []

    def notifier(self, **kwargs):
        options = {"host": "smtp.test", "port": 587, "user": "me@test",
                   "password": "app-password", "sender": "me@test",
                   "recipients": "owner@test, backup@test",
                   "mode": "starttls", "storage": self.agent.storage}
        options.update(kwargs)
        return EmailNotifier(**options)

    def test_disabled_notifier_is_a_noop(self):
        off = EmailNotifier(storage=self.agent.storage)
        self.assertFalse(off.enabled)
        self.assertFalse(off.send("hi", "body"))
        status = off.status()
        self.assertFalse(status["enabled"])
        self.assertIn("REALAI_SMTP_HOST", status["missing"])
        self.assertEqual(FakeSMTP.instances, [])
        # recipients are parsed from any reasonable separator
        self.assertEqual(parse_recipients("a@x.com, b@y.com;c@z.com d@w.com"),
                         ["a@x.com", "b@y.com", "c@z.com", "d@w.com"])
        self.assertEqual(parse_recipients("not-an-address"), [])
        self.assertEqual(parse_recipients(None), [])

    def test_starttls_delivery_and_login(self):
        notifier = self.notifier()
        self.assertTrue(notifier.enabled)
        with mock.patch.object(smtplib, "SMTP", FakeSMTP):
            self.assertTrue(notifier.send("subject", "hello body"))
        client = FakeSMTP.instances[0]
        self.assertEqual((client.host, client.port), ("smtp.test", 587))
        self.assertTrue(client.started_tls)
        self.assertEqual(client.logged_in,
                         ("me@test", "app-password"))
        self.assertTrue(client.quit_called)
        mail = client.sent[0]
        self.assertEqual(mail["subject"], "subject")
        self.assertEqual(mail["from"], "me@test")
        self.assertEqual(mail["to"], ["owner@test", "backup@test"])
        self.assertIn("hello body", mail["body"])
        counters = self.agent.storage.get_counters()["email"]
        self.assertEqual(counters["sent"], 1)
        # an unknown TLS mode falls back to the safe one
        self.assertEqual(self.notifier(mode="wat").mode, "starttls")

    def test_delivery_failure_never_raises(self):
        notifier = self.notifier(host="smtp.broken")
        with mock.patch.object(smtplib, "SMTP", BrokenSMTP):
            self.assertFalse(notifier.send("subject", "body"))
        counters = self.agent.storage.get_counters()["email"]
        self.assertEqual(counters["send_failed"], 1)
        self.assertNotIn("sent", counters)

    def test_cooldown_dedups_repeats(self):
        notifier = self.notifier()
        with mock.patch.object(smtplib, "SMTP", FakeSMTP):
            self.assertTrue(notifier.notify_access_request(
                "mira", note="hi", agent_name="REAL"))
            # the same request twice in a row must not spam the owner
            self.assertFalse(notifier.notify_access_request("mira"))
            self.assertTrue(notifier.notify_access_request("bob"))
        self.assertEqual(len(FakeSMTP.instances), 2)
        first = FakeSMTP.instances[0].sent[0]
        self.assertIn("mira", first["subject"])
        self.assertIn("PENDING", first["body"])
        self.assertIn("/approve", first["body"])
        counters = self.agent.storage.get_counters()["email"]
        self.assertEqual(counters["sent"], 2)
        self.assertEqual(counters["skipped_cooldown"], 1)
        # the password is never part of the diagnostic status
        self.assertNotIn("app-password", json.dumps(notifier.status()))


# ======================================================== serve + environment

class TestServeConfiguration(unittest.TestCase):
    def test_serve_honours_realai_environment(self):
        """``serve`` used to rebuild a default Config and ignore REALAI_*."""
        env = {
            "REALAI_DATA_DIR": "/tmp/realai-env-test",
            "REALAI_HOST": "127.0.0.1",
            "REALAI_PORT": "8123",
            "REALAI_AGENT_NAME": "NOVA",
            "REALAI_OWNER_NAME": "Boss",
            "REALAI_WEB_TOKEN": "tok",
            "REALAI_TICK_SECONDS": "42",
            "REALAI_DEMO_RATE_PER_MIN": "5",
            "REALAI_DEMO_BURST": "2",
            "REALAI_CONVERSATION_TURNS": "7",
            "REALAI_SMTP_HOST": "smtp.gmail.com",
            "REALAI_SMTP_PORT": "465",
            "REALAI_SMTP_USER": "owner@gmail.com",
            "REALAI_SMTP_PASSWORD": "abcd efgh ijkl mnop",
            "REALAI_SMTP_TO": "owner@gmail.com",
            "REALAI_SMTP_TLS": "ssl",
            "REALAI_BRAND_TAGLINE": "Custom tagline.",
        }
        with mock.patch.dict(os.environ, env, clear=False):
            cfg = Config.from_env()
        self.assertEqual(str(cfg.data_dir), "/tmp/realai-env-test")
        self.assertEqual(cfg.host, "127.0.0.1")
        self.assertEqual(cfg.port, 8123)
        self.assertEqual(cfg.agent_name, "NOVA")
        self.assertEqual(cfg.owner_name, "Boss")
        self.assertEqual(cfg.web_token, "tok")
        self.assertEqual(cfg.tick_seconds, 42.0)
        self.assertEqual(cfg.demo_rate_per_min, 5)
        self.assertEqual(cfg.demo_burst, 2)
        self.assertEqual(cfg.conversation_turns, 7)
        self.assertEqual(cfg.brand_tagline, "Custom tagline.")
        self.assertEqual(cfg.smtp_host, "smtp.gmail.com")
        self.assertEqual(cfg.smtp_port, 465)
        self.assertEqual(cfg.smtp_tls, "ssl")
        self.assertTrue(cfg.smtp_password)

        notifier = EmailNotifier.from_config(cfg, None)
        self.assertTrue(notifier.enabled)
        self.assertEqual(notifier.mode, "ssl")
        self.assertEqual(notifier.recipients, ["owner@gmail.com"])

        # and the CLI defaults are None, so an untyped flag cannot clobber
        # the environment-derived config
        from realaiagent.__main__ import build_parser
        args = build_parser().parse_args(["serve"])
        for flag in ("host", "port", "data", "tick", "name"):
            self.assertIsNone(getattr(args, flag), flag)
        typed = build_parser().parse_args(["serve", "--port", "9999"])
        self.assertEqual(typed.port, 9999)


if __name__ == "__main__":
    unittest.main()
